SAMPLES = ['Sample1', 'Sample2']

rule all:
	input:
		expand('results/{sample}.txt', sample = SAMPLES)
		
rule extend:
	input:
		o1 = 'results/{sample}.txt'
	output:
		'results/test.txt'
	shell:
		'echo {input.o1} > {output}'
		
rule quantify_genes:
	input:
		genome = 'data/genome.fa',
		r1 = 'data/{sample}.R1.fastq.gz',
		r2 = 'data/{sample}.R2.fastq.gz',
		r3 = 'data/{sample}.R3.fastq.gz'
	output:
		'results/{sample}.txt' 
	shell:
		'echo {input.genome} {input.r1} {input.r2} {input.r3} > {output}'
		

rule clean:
	shell: 
		'rm results/*.txt' 
